// Main Worker entry point for Cloudflare Workers
// Handles both HTTP requests (via compiled Pages Functions) and scheduled events (native cron)

/// <reference types="@cloudflare/workers-types" />

import type { Env } from '../functions/types';

// This is a temporary wrapper that loads the compiled Pages Functions worker
// and adds native cron trigger support

interface WorkerModule {
  default: {
    fetch?: (request: Request, env: Env, ctx: ExecutionContext) => Promise<Response>;
  };
}

// Scheduled handler for native cron triggers
const scheduled: ExportedHandlerScheduledHandler<Env> = async (controller: ScheduledController, env: Env, _ctx: ExecutionContext) => {
  console.log('[Cron] Scheduled event triggered:', controller.cron, 'at', new Date().toISOString());

  try {
    // Import the onSchedule function from scheduled.ts
    const { onSchedule } = await import('../functions/scheduled');

    // Call the Pages Function onSchedule handler
    await onSchedule({ env });

    console.log('[Cron] Scheduled task completed successfully');
  } catch (error) {
    console.error('[Cron] Scheduled task failed:', error);
    // Re-throw to mark the cron execution as failed in Cloudflare dashboard
    throw error;
  }
};

// HTTP request handler (delegates to compiled Pages Functions)
const fetch: ExportedHandlerFetchHandler<Env> = async (request: Request, env: Env, ctx: ExecutionContext): Promise<Response> => {
  // Import the compiled Pages Functions worker dynamically
  // This file is generated by 'wrangler pages functions build' during the build process
  // @ts-expect-error - File is generated at build time and doesn't exist during type-checking
  const pagesWorker = await import('../dist/_worker.js/index.js') as any as WorkerModule;
  if (pagesWorker.default.fetch) {
    return pagesWorker.default.fetch(request, env, ctx);
  }
  return new Response('Worker not initialized', { status: 500 });
};

// Export all handlers as a single default export
export default {
  fetch,
  scheduled,
};
