// Main Worker entry point for Cloudflare Workers
// Handles both HTTP requests (via compiled Pages Functions) and scheduled events (native cron)

/// <reference types="@cloudflare/workers-types" />

import type { Env } from '../functions/types';

// This is a temporary wrapper that loads the compiled Pages Functions worker
// and adds native cron trigger support

interface WorkerModule {
  default: {
    fetch?: (request: Request, env: Env, ctx: ExecutionContext) => Promise<Response>;
  };
}

// Default export: HTTP request handler (delegates to compiled Pages Functions)
const worker: ExportedHandler<Env> = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    // Import the compiled Pages Functions worker dynamically
    // This file is generated by 'wrangler pages functions build' during the build process
    const pagesWorker = await import('../dist/_worker.js/index.js') as any as WorkerModule;
    if (pagesWorker.default.fetch) {
      return pagesWorker.default.fetch(request, env, ctx);
    }
    return new Response('Worker not initialized', { status: 500 });
  },
};

export default worker;

// Export scheduled handler for native cron triggers
export const scheduled: ExportedHandlerScheduledHandler<Env> = async (controller: ScheduledController, env: Env, ctx: ExecutionContext) => {
  console.log('[Cron] Scheduled event triggered:', controller.cron, 'at', new Date().toISOString());

  try {
    // Import the onSchedule function from scheduled.ts
    const { onSchedule } = await import('../functions/scheduled');

    // Call the Pages Function onSchedule handler
    // The onSchedule function only needs env
    const response = await onSchedule({ env });

    console.log('[Cron] Scheduled task completed successfully with status:', response?.status);
  } catch (error) {
    console.error('[Cron] Scheduled task failed:', error);
    // Re-throw to mark the cron execution as failed in Cloudflare dashboard
    throw error;
  }
};
